import FranchisePayout from '../../models/FranchisePayout.model.js';
import MasterFranchiseRelation from '../../models/MasterFranchiseRelation.model.js';
import MasterFranchisePayout from '../../models/MasterFranchisePayout.model.js';
import FranchiseBvState from '../../models/FranchiseBvState.model.js';
import mongoose from 'mongoose';

/**
 * Calculates and creates differential and override payouts for Master Franchises.
 * This runs AFTER the main franchise payout cron job finishes.
 * It reads the "Base Stats" generated by the main job and awards the extra +5% and +₹10.
 */
export const generateDifferentialMasterPayouts = async () => {
    // Determine the historical month being processed
    const now = new Date();
    // Month is zero-indexed in JS (Jan=0, Feb=1, etc.)
    let targetMonth = now.getMonth() === 0 ? 12 : now.getMonth();
    let targetYear = now.getMonth() === 0 ? now.getFullYear() - 1 : now.getFullYear();

    console.log(`[Master Payout Engine] Starting generation for ${targetMonth}/${targetYear}`);

    const session = await mongoose.startSession();
    session.startTransaction();

    try {
        // 1. Fetch all active Master Franchises and their Sub-Franchise IDs
        const masters = await MasterFranchiseRelation.find({ isActive: true }).session(session);

        let differentialCount = 0;
        let overrideCount = 0;

        for (const master of masters) {
            const masterId = master.masterId;

            // --- A. Master's Own Differential Earning (Target: 15% BV, ₹50 PV) ---
            // Fetch normal payouts given to the Master by the main cron job
            const masterBasePayouts = await FranchisePayout.find({
                franchiseId: masterId,
                month: targetMonth,
                year: targetYear
            }).session(session);

            let masterTotalBv = 0;
            let masterTotalPv = 0;

            for (const pb of masterBasePayouts) {
                if (pb.payoutType === 'BV') masterTotalBv += pb.totalBv;
                if (pb.payoutType === 'PV') masterTotalPv += pb.totalPv;
            }

            // If master did business, give them the differential (+15% BV, +₹50 PV)
            if (masterTotalBv > 0 || masterTotalPv > 0) {
                const diffBvGross = masterTotalBv * 0.15; // Extra 15%
                const diffPvGross = masterTotalPv * 50;   // Extra ₹50 per PV
                
                const totalGross = diffBvGross + diffPvGross;
                if (totalGross > 0) {
                    const adminCharge = totalGross * 0.05;
                    const tdsCharge = totalGross * 0.02;
                    const netPayout = totalGross - adminCharge - tdsCharge;

                    await MasterFranchisePayout.findOneAndUpdate(
                        {
                            masterId,
                            sourceFranchiseId: null, // Indicates own sales
                            earningType: 'OWN_DIFFERENTIAL',
                            month: targetMonth,
                            year: targetYear
                        },
                        {
                            $setOnInsert: {
                                masterId,
                                sourceFranchiseId: null,
                                earningType: 'OWN_DIFFERENTIAL',
                                month: targetMonth,
                                year: targetYear,
                                baseBv: masterTotalBv,
                                basePv: masterTotalPv,
                                grossPayout: parseFloat(totalGross.toFixed(2)),
                                adminCharge: parseFloat(adminCharge.toFixed(2)),
                                tdsCharge: parseFloat(tdsCharge.toFixed(2)),
                                netPayout: parseFloat(netPayout.toFixed(2)),
                                status: 'pending'
                            }
                        },
                        { upsert: true, session }
                    );
                    differentialCount++;
                }
            }

            // --- B. Override Commissions from Sub-Franchises (Target: 5% BV, ₹10 PV) ---
            for (const subId of master.subFranchises) {
                const subBasePayouts = await FranchisePayout.find({
                    franchiseId: subId,
                    month: targetMonth,
                    year: targetYear
                }).session(session);

                let subTotalBv = 0;
                let subTotalPv = 0;

                for (const sb of subBasePayouts) {
                    if (sb.payoutType === 'BV') subTotalBv += sb.totalBv;
                    if (sb.payoutType === 'PV') subTotalPv += sb.totalPv;
                }

                // If sub-franchise did business, give master override commission
                if (subTotalBv > 0 || subTotalPv > 0) {
                    const overBvGross = subTotalBv * 0.05; // 5% of Sub's BV
                    const overPvGross = subTotalPv * 10;   // ₹10 per Sub's PV

                    const totalOverGross = overBvGross + overPvGross;
                    if (totalOverGross > 0) {
                        const adminCharge = totalOverGross * 0.05;
                        const tdsCharge = totalOverGross * 0.02;
                        const netPayout = totalOverGross - adminCharge - tdsCharge;

                        await MasterFranchisePayout.findOneAndUpdate(
                            {
                                masterId,
                                sourceFranchiseId: subId, // Tagged to the sub
                                earningType: 'SUB_OVERRIDE',
                                month: targetMonth,
                                year: targetYear
                            },
                            {
                                $setOnInsert: {
                                    masterId,
                                    sourceFranchiseId: subId,
                                    earningType: 'SUB_OVERRIDE',
                                    month: targetMonth,
                                    year: targetYear,
                                    baseBv: subTotalBv,
                                    basePv: subTotalPv,
                                    grossPayout: parseFloat(totalOverGross.toFixed(2)),
                                    adminCharge: parseFloat(adminCharge.toFixed(2)),
                                    tdsCharge: parseFloat(tdsCharge.toFixed(2)),
                                    netPayout: parseFloat(netPayout.toFixed(2)),
                                    status: 'pending'
                                }
                            },
                            { upsert: true, session }
                        );
                        overrideCount++;
                    }
                }
            }
        }

        await session.commitTransaction();
        session.endSession();

        console.log(`[Master Payout Engine] Successfully created ${differentialCount} differentials and ${overrideCount} overrides.`);
        return { success: true, differentialCount, overrideCount };
        
    } catch (error) {
        await session.abortTransaction();
        session.endSession();
        console.error('[Master Payout Engine] FATAL ERROR:', error);
        throw error;
    }
};

/**
 * Calculates LIVE projected earnings for the CURRENT month for a specific Master Franchise.
 * This reads the ongoing real-time BV/PV states (FranchiseBvState) which update on every new bill.
 * Completely isolated from core calculation system logic.
 */
export const getLiveProjectedEarnings = async (masterId) => {
    try {
        const masterRelation = await MasterFranchiseRelation.findOne({ masterId, isActive: true });
        if (!masterRelation) {
            return {
                isActiveMaster: false,
                projectedOwnDifferential: 0,
                projectedSubOverride: 0,
                totalProjectedGross: 0,
                totalProjectedNet: 0
            };
        }

        // 1. Calculate Own Differential (Live) - Target: 15% BV, ₹50 PV
        const masterBvState = await FranchiseBvState.findOne({ franchiseId: masterId });
        let ownGross = 0;
        let ownAdminCharge = 0;
        let ownTdsCharge = 0;
        let ownNet = 0;

        if (masterBvState) {
             const bvGross = (masterBvState.currentMonthRepurchaseBv || 0) * 0.15;
             const pvGross = (masterBvState.currentMonthFirstPurchasePv || 0) * 50;
             ownGross = bvGross + pvGross;
             ownAdminCharge = ownGross * 0.05;
             ownTdsCharge = ownGross * 0.02;
             ownNet = ownGross - ownAdminCharge - ownTdsCharge;
        }

        // 2. Calculate Sub-Network Override (Live) with Detailed Individual Breakdown
        let subGross = 0;
        let subAdminCharge = 0;
        let subTdsCharge = 0;
        let subNet = 0;
        let subNetworkDetails = [];

        if (masterRelation.subFranchises && masterRelation.subFranchises.length > 0) {
             const subBvStates = await FranchiseBvState.find({ franchiseId: { $in: masterRelation.subFranchises } })
                 .populate('franchiseId', 'shopName vendorId')
                 .lean();

             for (const state of subBvStates) {
                 if (!state.franchiseId) continue;
                 
                 const bv = state.currentMonthRepurchaseBv || 0;
                 const pv = state.currentMonthFirstPurchasePv || 0;
                 
                 const sbGross = bv * 0.05;
                 const spGross = pv * 10;
                 const totalContrib = sbGross + spGross;

                 if (totalContrib > 0) {
                     const individualAdminCharge = totalContrib * 0.05;
                     const individualTdsCharge = totalContrib * 0.02;
                     const individualNet = totalContrib - individualAdminCharge - individualTdsCharge;

                     subGross += totalContrib;
                     subAdminCharge += individualAdminCharge;
                     subTdsCharge += individualTdsCharge;
                     subNet += individualNet;

                     subNetworkDetails.push({
                         franchiseId: state.franchiseId._id,
                         shopName: state.franchiseId.shopName,
                         vendorId: state.franchiseId.vendorId,
                         bvContribution: bv,
                         pvContribution: pv,
                         earnedOverride: totalContrib,
                         adminCharge: individualAdminCharge,
                         tdsCharge: individualTdsCharge,
                         netOverride: individualNet
                     });
                 }
             }

             // Sort details by highest contribution
             subNetworkDetails.sort((a, b) => b.earnedOverride - a.earnedOverride);
        }

        const totalGross = ownGross + subGross;
        const totalAdminCharge = ownAdminCharge + subAdminCharge;
        const totalTdsCharge = ownTdsCharge + subTdsCharge;
        const totalNet = ownNet + subNet;

        return {
            isActiveMaster: true,
            // Own Details
            projectedOwnDifferential: parseFloat(ownGross.toFixed(2)),
            ownAdminCharge: parseFloat(ownAdminCharge.toFixed(2)),
            ownTdsCharge: parseFloat(ownTdsCharge.toFixed(2)),
            ownNet: parseFloat(ownNet.toFixed(2)),
            
            // Sub Details
            projectedSubOverride: parseFloat(subGross.toFixed(2)),
            subAdminCharge: parseFloat(subAdminCharge.toFixed(2)),
            subTdsCharge: parseFloat(subTdsCharge.toFixed(2)),
            subNet: parseFloat(subNet.toFixed(2)),

            // Total Aggregates
            totalProjectedGross: parseFloat(totalGross.toFixed(2)),
            adminCharge: parseFloat(totalAdminCharge.toFixed(2)),
            tdsCharge: parseFloat(totalTdsCharge.toFixed(2)),
            totalProjectedNet: parseFloat(totalNet.toFixed(2)),
            subNetworkDetails // newly added detailed array
        };
    } catch (error) {
        console.error('[Master Payout Service] Failed to calculate live earnings:', error);
        throw error;
    }
};
